### ISSUE TITLE
decode big string error

### ISSUE THREAD

**Issue by vsouza** [Zewo/Base64#7]
I'm trying to decode a a large string and the return is only a few caracateres.

this is the content: https://api.github.com/repos/vsouza/awesome-ios/git/blobs/2982828382129f0c6ffd706dd1e2b8dfc1cf55a8
this is the return that I've got: `<img src="https://raw.githubusercontent.com/v`

The expected return is a huge HTML data, like source code of this page: http://awesomeios.com/
It seems to me that it is something related to the line breaks `\n`
Any chance I have forgotten to implement something?

Thanks guys

**Comment by lfarah** [comment]
+1

**Comment by Danappelxx** [comment]
Can you show the code you used to fetch it? There's a chance that this isn't a Base64 bug.

**Comment by Danappelxx** [comment]
Ok, I was unable to reproduce this exact bug because in my case the decoder wasn't working at all... @paulofaria can you help us out here? I'm not familiar enough with Base64 to be of use.

Edit: Ok never mind it works for smaller strings but it does seem to fail inconsistently for me, and more importantly does not throw an error on malformed data it seems.

**Comment by vsouza** [comment]
@Danappelxx & @paulofaria this is the code:

``` swift
    public func getContent(uri: String) -> Data? {
        do {
            let client = try! Client(uri: Constants.General.mainURL)
            var response = try client.get(uri)
            let buffer = try response.body.becomeBuffer()
            let parsed = try! JSONParser().parse(data: buffer)
      let treeDict = try! parsed.asDictionary()["tree"]!.asArray()
      for tree in treeDict {
        if tree["path"] == "README.md" {
                let url = try! tree["url"]!.asString()
                var response2 = try client.get("/repos/vsouza/awesome-ios/git/blobs/2982828382129f0c6ffd706dd1e2b8dfc1cf55a8")
                let buffer2 = try response2.body.becomeBuffer()
              let parsed2 = try! JSONParser().parse(data: buffer2)
                let baseData = try! parsed2["content"]!.asString()
          self.decoded = Base64.decode(baseData)
            }
      }
        } catch {
        print("Error")
            return nil
        }
    return self.decoded
    }

```

**Comment by vsouza** [comment]
I made another implementation using Swift 3.0. I don't get this error anymore. 

https://github.com/vsouza/VSBase64
